"""add mesas vendas clean

Revision ID: 779c17873764
Revises: fc674bc0909d
Create Date: 2026-09-30 14:44:28.357782

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '779c17873764'
down_revision: Union[str, None] = 'fc674bc0909d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('capacidade', sa.Integer(), server_default='4', nullable=False),
    sa.Column('status', sa.Enum('LIVRE', 'OCUPADA', 'RESERVADA', name='mesastatus'), server_default='LIVRE', nullable=False),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'numero', name='uq_mesa_empresa_numero')
    )
    op.create_index(op.f('ix_mesas_empresa_id'), 'mesas', ['empresa_id'], unique=False)
    op.create_table('vendas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('BALCAO', 'MESA', name='vendatipo'), nullable=False),
    sa.Column('mesa_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dinheiro_recebido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('troco', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'CONCLUIDA', 'CANCELADA', name='vendastatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'numero', name='uq_venda_empresa_numero')
    )
    op.create_index(op.f('ix_vendas_empresa_id'), 'vendas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_vendas_mesa_id'), 'vendas', ['mesa_id'], unique=False)
    op.create_table('venda_itens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venda_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('nome_produto', sa.String(length=150), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('preco_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tem_iva', sa.Boolean(), nullable=False),
    sa.Column('iva_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva_valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('empresas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('products', 'tipo',
               existing_type=postgresql.ENUM('GENERAL', 'RESTAURANT_DISH', 'RESTAURANT_INGREDIENT', 'RESTAURANT_DRINK', 'SERVICE', 'KIT', name='producttype'),
               server_default='GENERAL',
               existing_nullable=False)
    op.alter_column('products', 'unidade',
               existing_type=postgresql.ENUM('UNIT', 'KG', 'LITER', 'HOUR', 'DAY', 'TASK', 'PORTION', 'UN', name='productunit'),
               server_default='UNIT',
               existing_nullable=False)
    op.alter_column('products', 'preco_custo',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default='0',
               existing_nullable=False)
    op.alter_column('products', 'iva',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default='0',
               existing_nullable=False)
    op.alter_column('products', 'tem_iva',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('products', 'ativo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('products', 'controlar_stock',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('products', 'allow_negative',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('products', 'stock_atual',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               server_default='0',
               existing_nullable=False)
    op.alter_column('products', 'stock_minimo',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               server_default='0',
               existing_nullable=False)
    op.alter_column('products', 'is_modifiable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('products', 'requires_booking',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('products', 'requires_staff',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_empresas', 'role',
               existing_type=postgresql.ENUM('DONO', 'FUNCIONARIO', name='roleenum'),
               server_default='FUNCIONARIO',
               existing_nullable=False)
    op.alter_column('user_empresas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'empresa_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('DONO', 'FUNCIONARIO', name='roleenum'),
               server_default='FUNCIONARIO',
               nullable=False)
    op.alter_column('users', 'ativo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'ativo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('DONO', 'FUNCIONARIO', name='roleenum'),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'empresa_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_empresas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_empresas', 'role',
               existing_type=postgresql.ENUM('DONO', 'FUNCIONARIO', name='roleenum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'requires_staff',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'requires_booking',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'is_modifiable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'stock_minimo',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'stock_atual',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'allow_negative',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'controlar_stock',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'ativo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'tem_iva',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'iva',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'preco_custo',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'unidade',
               existing_type=postgresql.ENUM('UNIT', 'KG', 'LITER', 'HOUR', 'DAY', 'TASK', 'PORTION', 'UN', name='productunit'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'tipo',
               existing_type=postgresql.ENUM('GENERAL', 'RESTAURANT_DISH', 'RESTAURANT_INGREDIENT', 'RESTAURANT_DRINK', 'SERVICE', 'KIT', name='producttype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_table('venda_itens')
    op.drop_index(op.f('ix_vendas_mesa_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_empresa_id'), table_name='vendas')
    op.drop_table('vendas')
    op.drop_index(op.f('ix_mesas_empresa_id'), table_name='mesas')
    op.drop_table('mesas')
    # ### end Alembic commands ###
