"""add user_empresas

Revision ID: a8683c27c3f3
Revises:
Create Date: 2026-09-29 16:49:00.330589

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8683c27c3f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.create_table('user_empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('DONO', 'FUNCIONARIO', name='roleenum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'empresa_id', name='uq_user_empresa')
    )
    op.create_index(op.f('ix_user_empresas_empresa_id'), 'user_empresas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_user_empresas_user_id'), 'user_empresas', ['user_id'], unique=False)
    op.execute("INSERT INTO user_empresas (id, user_id, empresa_id, role, created_at) SELECT gen_random_uuid(), id, empresa_id, role, created_at FROM users WHERE empresa_id IS NOT NULL ON CONFLICT DO NOTHING")
    # ... resto igual
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('DONO', 'FUNCIONARIO', name='roleenum'),
               nullable=True)
    op.alter_column('users', 'empresa_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_user_empresas_user_id'), table_name='user_empresas')
    op.drop_index(op.f('ix_user_empresas_empresa_id'), table_name='user_empresas')
    op.drop_table('user_empresas')
    # ### end Alembic commands ###
